'use client'

import { useState } from 'react'
import { ArrowLeft, Code2, FileText, Save } from 'lucide-react'
import Link from 'next/link'
import { useToast } from '@/components/ui/toast'

export default function CreateBlogPage() {
  const [htmlMode, setHtmlMode] = useState(false)
  const { toast } = useToast()
  return <div className="max-w-3xl"><Link href="/admin/blog" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-primary"><ArrowLeft className="size-4" /> Back to blog CMS</Link><div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Content studio</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Create blog post</h1><p className="mt-1 text-sm text-muted-foreground">Draft practical notes for the PrintForge community.</p></div><FileText className="size-8 text-primary" /></div><div className="mt-8 space-y-5 rounded-md border border-border bg-card p-6"><label className="block"><span className="mb-2 block text-sm font-semibold">Title</span><input className="h-11 w-full rounded-md border border-border bg-background px-3 outline-none focus:border-ring" placeholder="A useful idea for makers" /></label><label className="block"><span className="mb-2 block text-sm font-semibold">Excerpt</span><textarea className="min-h-24 w-full rounded-md border border-border bg-background p-3 outline-none focus:border-ring" placeholder="A short description for search and previews" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-sm font-semibold">Keywords</span><input className="h-11 w-full rounded-md border border-border bg-background px-3 outline-none focus:border-ring" placeholder="materials, printing" /></label><label className="block"><span className="mb-2 block text-sm font-semibold">Read time</span><input type="number" className="h-11 w-full rounded-md border border-border bg-background px-3 outline-none focus:border-ring" placeholder="6" /></label></div><div><div className="mb-2 flex items-center justify-between"><span className="text-sm font-semibold">Content</span><button type="button" onClick={() => setHtmlMode((current) => !current)} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-1.5 text-xs font-semibold">{htmlMode ? <FileText className="size-3.5" /> : <Code2 className="size-3.5" />}{htmlMode ? 'Rich text mode' : 'HTML mode'}</button></div><textarea className={`w-full rounded-md border border-border bg-background p-3 outline-none focus:border-ring ${htmlMode ? 'min-h-72 font-mono text-sm' : 'min-h-72'}`} placeholder={htmlMode ? '<p>Write safe HTML here...</p>' : 'Start writing your article...'} /></div><div className="flex justify-end"><button type="button" onClick={() => toast('Draft saved', { variant: 'success', description: 'The post is saved in mock preview mode.' })} className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Save className="size-4" /> Save draft</button></div></div></div>
}
