'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { CheckCircle2, ShieldCheck } from 'lucide-react'
import { AuthForm } from '@/components/auth/auth-form'
import { Button } from '@/components/ui/button'
import { Input, Label } from '@/components/ui/input'
import { useAuth } from '@/lib/auth-context'
import { useCart } from '@/lib/cart-context'
import { formatPrice } from '@/lib/utils'

const payments = ['UPI / PhonePe / GPay', 'Credit / Debit Card', 'Netbanking', 'Cash on Delivery']
const shippingMethods = [
  { id: 'standard', name: 'Standard delivery', detail: '3–7 business days', price: 0 },
  { id: 'express', name: 'Express delivery', detail: '1–2 business days', price: 149 },
]

export function CheckoutPage() {
  const { user } = useAuth()
  const { items, subtotal, clear } = useCart()
  const [showAuth, setShowAuth] = useState<'login' | 'register'>('login')
  const [payment, setPayment] = useState(payments[0])
  const [shipping, setShipping] = useState('standard')
  const [placed, setPlaced] = useState(false)
  const shippingFee = shippingMethods.find((method) => method.id === shipping)?.price ?? 0
  const gst = subtotal * 0.18
  const orderTotal = subtotal + gst + shippingFee

  if (placed) return <main className="flex min-h-[70vh] items-center justify-center px-4 py-16"><div className="w-full max-w-md rounded-2xl border border-border bg-card p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto size-14 text-success" /><h1 className="mt-5 text-2xl font-black">Order placed successfully</h1><p className="mt-2 text-sm text-muted-foreground">Your order has been received and will be prepared shortly.</p><Button className="mt-6 w-full" render={<Link href="/account" />}>View order status</Button></div></main>

  return <main className="min-h-screen w-full bg-background px-4 py-8 sm:px-6 lg:px-10"><div className="mx-auto max-w-7xl"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">PrintForge checkout</p><h1 className="mt-2 text-3xl font-black tracking-tight">Complete your order</h1><p className="mt-2 text-muted-foreground">Made-to-order products, carefully packed and delivered to you.</p></div><div className="grid gap-8 lg:grid-cols-[1fr_380px] lg:items-start"><div className="space-y-6">
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">1</span><div><h2 className="font-bold">Account</h2><p className="text-sm text-muted-foreground">Sign in to save your order details.</p></div></div>{user ? <div className="mt-5 rounded-xl bg-muted p-4"><p className="font-semibold">{user.full_name}</p><p className="text-sm text-muted-foreground">{user.email}</p></div> : <div className="mt-5"><div className="mb-4 flex gap-2"><Button type="button" variant={showAuth === 'login' ? 'default' : 'outline'} onClick={() => setShowAuth('login')}>Log in</Button><Button type="button" variant={showAuth === 'register' ? 'default' : 'outline'} onClick={() => setShowAuth('register')}>Sign up</Button></div><AuthForm mode={showAuth} compact /></div>}</section>
    <form id="checkout-form" onSubmit={(event) => { event.preventDefault(); if (event.currentTarget.reportValidity()) setPlaced(true) }} className="space-y-6"><section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">2</span><div><h2 className="font-bold">Shipping address</h2><p className="text-sm text-muted-foreground">Where should we send your order?</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><Label htmlFor="name">Full name</Label><Input id="name" name="name" required defaultValue={user?.full_name ?? ''} /></div><div><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" required defaultValue={user?.email ?? ''} /></div><div className="sm:col-span-2"><Label htmlFor="address1">Address line 1</Label><Input id="address1" name="address1" required /></div><div className="sm:col-span-2"><Label htmlFor="address2">Address line 2 <span className="font-normal text-muted-foreground">(optional)</span></Label><Input id="address2" name="address2" /></div><div><Label htmlFor="city">City</Label><Input id="city" name="city" required /></div><div><Label htmlFor="state">State</Label><Input id="state" name="state" required /></div><div><Label htmlFor="zip">ZIP / PIN code</Label><Input id="zip" name="zip" required pattern="[0-9]{5,6}" title="Enter a valid 5 or 6 digit ZIP or PIN code" /></div><div><Label htmlFor="country">Country</Label><Input id="country" name="country" required defaultValue="India" /></div><div><Label htmlFor="phone">Phone</Label><Input id="phone" name="phone" type="tel" required /></div></div></section>
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">3</span><div><h2 className="font-bold">Shipping method</h2><p className="text-sm text-muted-foreground">Choose how quickly you would like it delivered.</p></div></div><div className="mt-5 grid gap-3">{shippingMethods.map((method) => <label key={method.id} className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-border p-4 transition-colors hover:border-primary has-[:checked]:border-primary has-[:checked]:bg-primary/5"><span className="flex items-center gap-3"><input type="radio" name="shipping" value={method.id} checked={shipping === method.id} onChange={() => setShipping(method.id)} className="accent-primary" /><span><span className="block text-sm font-semibold">{method.name}</span><span className="block text-xs text-muted-foreground">{method.detail}</span></span></span><span className="text-sm font-semibold">{method.price ? formatPrice(method.price) : 'FREE'}</span></label>)}</div></section>
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><h2 className="font-bold">Payment method</h2><div className="mt-5 grid gap-3">{payments.map((option) => <label key={option} className="flex cursor-pointer items-center gap-3 rounded-xl border border-border p-4 transition-colors hover:border-primary has-[:checked]:border-primary has-[:checked]:bg-primary/5"><input type="radio" name="payment" value={option} checked={payment === option} onChange={() => setPayment(option)} className="accent-primary" /><span className="text-sm font-medium">{option}</span></label>)}</div></section></form>
  </div><aside className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-7 lg:sticky lg:top-6"><h2 className="text-lg font-black">Order summary</h2>{items.length === 0 ? <div className="py-10 text-center"><p className="text-sm text-muted-foreground">Your cart is empty.</p><Button className="mt-4" render={<Link href="/shop" />}>Browse products</Button></div> : <><ul className="mt-5 divide-y divide-border">{items.map((item) => <li key={item.key} className="flex gap-3 py-3"><div className="relative size-16 shrink-0 overflow-hidden rounded-lg bg-muted"><Image src={item.image || '/placeholder.svg'} alt={item.product_name} fill className="object-cover" sizes="64px" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.product_name}</p><p className="text-xs text-muted-foreground">Qty {item.quantity} · {item.material.name} · {item.color.name}</p><p className="mt-1 text-sm">{formatPrice(item.unit_price * item.quantity)}</p></div></li>)}</ul><div className="mt-5 space-y-3 border-t border-border pt-5 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span>{formatPrice(subtotal)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Estimated GST (18%)</span><span>{formatPrice(gst)}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Shipping</span><span>{shippingFee ? formatPrice(shippingFee) : 'FREE'}</span></div><div className="flex justify-between border-t border-border pt-4 text-base font-black"><span>Total</span><span>{formatPrice(orderTotal)}</span></div></div><Button form="checkout-form" className="mt-6 w-full" size="lg" disabled={!user}>Continue to Payment</Button><p className="mt-3 flex items-center justify-center gap-2 text-center text-xs text-muted-foreground"><ShieldCheck className="size-3.5" /> Secure checkout</p></>}</aside></div></div></main>
}
