import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CalendarDays, Clock3 } from 'lucide-react'
import { mockBlogPosts } from '@/data/mockData'

export default function BlogPage() {
  const posts = [...mockBlogPosts].sort((a, b) => +new Date(b.published_at) - +new Date(a.published_at))
  return <main className="mx-auto max-w-6xl px-6 py-14 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">From the workshop</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-foreground text-balance sm:text-5xl">Notes on making things better.</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">Material guides, design lessons, and a look behind the scenes at made-to-order 3D printing.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2">{posts.map((post) => <article key={post.id} className="group overflow-hidden border border-border bg-card"><Link href={`/blog/${post.slug}`} className="block"><div className="relative aspect-[16/9] overflow-hidden bg-muted"><Image src={post.image} alt={post.title} fill className="object-cover transition-transform duration-500 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 50vw" /></div><div className="p-6"><div className="flex flex-wrap items-center gap-x-3 gap-y-2 text-xs font-semibold uppercase tracking-wider text-primary"><span>{post.keywords[0]}</span><span className="text-border">/</span><span className="inline-flex items-center gap-1.5 text-muted-foreground normal-case tracking-normal"><CalendarDays className="size-3.5" />{new Date(post.published_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span></div><h2 className="mt-4 text-2xl font-semibold leading-tight text-foreground group-hover:text-primary">{post.title}</h2><p className="mt-3 line-clamp-2 leading-7 text-muted-foreground">{post.excerpt}</p><div className="mt-5 flex items-center justify-between text-sm text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Clock3 className="size-4" />{post.read_time} min read</span><span className="inline-flex items-center gap-2 font-semibold text-primary">Read article <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></div></div></Link></article>)}</div></main>
}
