'use client'

import { Boxes, PackageCheck, ShieldCheck, ShoppingBag, Users, DollarSign } from 'lucide-react'
import Link from 'next/link'
import { useAuth } from '@/lib/auth-context'
import { mockOrders, mockProducts, mockProfiles } from '@/data/mockData'

export default function AdminPage() {
  const { user } = useAuth()
  const master = user?.role === 'MASTER_ADMIN'
  const orders = master ? mockOrders : mockOrders.filter((order) => order.status === 'PENDING' || order.status === 'PROCESSING')
  const cards = master ? [['Revenue', '$12,842', 'This month', DollarSign], ['Orders', String(mockOrders.length + 31), 'Across all channels', ShoppingBag], ['Products', String(mockProducts.length), 'Published catalog items', Boxes], ['Customers', String(mockProfiles.length + 118), 'Active accounts', Users]] : [['Open orders', String(orders.length), 'Awaiting fulfillment', PackageCheck], ['Inventory', String(mockProducts.length), 'Catalog items', Boxes], ['Scope', '2 areas', 'Orders + inventory', ShieldCheck]]
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{master ? 'Master control' : 'Operations desk'}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{master ? 'Business overview' : 'Fulfillment queue'}</h1><p className="mt-1 text-sm text-muted-foreground">Signed in as {user?.email ?? 'demo administrator'}.</p></div><span className="flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm"><ShieldCheck className="size-4 text-primary" /> {master ? 'Full access' : 'Scoped staff access'}</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, note, Icon]) => <div key={String(label)} className="rounded-md border border-border bg-card p-5"><Icon className="size-5 text-primary" /><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>)}</div><section className="mt-8 rounded-md border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-5"><div><h2 className="font-semibold">Recent orders</h2><p className="mt-1 text-sm text-muted-foreground">{master ? 'All recent customer activity.' : 'Orders assigned to your operations scope.'}</p></div><Link href="/admin/products" className="text-sm font-medium text-primary hover:underline">Manage inventory</Link></div><div className="divide-y divide-border">{orders.slice(0, 6).map((order) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="font-medium">{order.id}</p><p className="mt-1 text-sm text-muted-foreground">{order.items.length} items · ${order.total_amount.toFixed(2)}</p></div><span className="rounded-sm bg-muted px-2.5 py-1 text-xs font-semibold">{order.status}</span></div>)}</div></section></main>
}
