import Link from 'next/link'
import { ArrowRight, Check, Clock3, Layers3, Leaf, PenTool } from 'lucide-react'
import { notFound } from 'next/navigation'
import { BulkEnquiryForm } from '@/components/policies/bulk-enquiry-form'
import { Button } from '@/components/ui/button'
import { mockPolicies } from '@/data/mockData'

export function generateStaticParams() { return Object.keys(mockPolicies).concat(['about', 'printing-services', 'bulk-enquiry']).map((slug) => ({ slug })) }

const pillars = [{ title: 'Quality, every layer', text: 'We tune every print for clean edges, reliable fit, and a finish you will be proud to keep on your desk.', icon: Check }, { title: 'Less waste by design', text: 'Made-to-order production means we print what is needed, rather than filling a warehouse with unloved stock.', icon: Leaf }, { title: 'Craftsmanship matters', text: 'Thoughtful design, careful color selection, and a human eye on every order make the difference.', icon: PenTool }]

function PageIntro({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-foreground text-balance sm:text-5xl">{title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{children}</p></div> }

function AboutPage() { return <main className="mx-auto max-w-6xl px-6 py-14 lg:px-8"><PageIntro eyebrow="About PrintForge" title="Useful objects, made with intention.">We make custom-colored, made-to-order 3D printed products for desks, homes, and the people who like their everyday tools to feel personal.</PageIntro><section className="mt-16 grid gap-12 border-y border-border py-12 md:grid-cols-[1fr_1.5fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Our story</p><h2 className="mt-3 text-3xl font-semibold">From a spare-room printer to a small workshop.</h2></div><p className="text-lg leading-8 text-muted-foreground">PrintForge started with a simple idea: the objects around us should work better and look more like us. We began by printing small batches for friends, learning the quirks of every material and finish along the way. Today, each order is still made with that same care — printed only when it is needed, in the color you choose.</p></section><section className="mt-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">What we believe</p><div className="mt-6 grid gap-5 md:grid-cols-3">{pillars.map(({ title, text, icon: Icon }) => <div key={title} className="border border-border bg-card p-6"><Icon className="size-6 text-primary" /><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{text}</p></div>)}</div></section><div className="mt-16 flex flex-wrap items-center justify-between gap-5 bg-primary p-8 text-primary-foreground"><div><h2 className="text-2xl font-semibold">Find something for your space.</h2><p className="mt-2 text-primary-foreground/75">Browse the current collection and choose your finish.</p></div><Button asChild variant="secondary"><Link href="/shop">Shop the collection <ArrowRight className="size-4" /></Link></Button></div></main> }

function ServicesPage() { const steps = ['Submit a design or choose from our catalog', 'Get a clear quote for your quantity and finish', 'We print, inspect, and carefully pack your order', 'Your pieces ship directly from our workshop']
return <main className="mx-auto max-w-6xl px-6 py-14 lg:px-8"><PageIntro eyebrow="Print with us" title="Printing services for ideas at every scale.">From one-off custom parts to a coordinated run for your next event, our workshop turns digital designs into dependable physical objects.</PageIntro><section className="mt-14 grid gap-5 md:grid-cols-2"><div className="border border-border bg-card p-7"><Layers3 className="size-6 text-primary" /><h2 className="mt-5 text-2xl font-semibold">What we offer</h2><ul className="mt-5 space-y-3 text-muted-foreground">{['Custom designs and prototypes', 'Bulk and business orders', 'PLA, PETG, and ABS material options', 'Custom color matching and branding'].map((item) => <li key={item} className="flex gap-3"><Check className="mt-1 size-4 shrink-0 text-primary" />{item}</li>)}</ul></div><div className="border border-border bg-secondary p-7"><Clock3 className="size-6 text-primary" /><h2 className="mt-5 text-2xl font-semibold">Turnaround</h2><p className="mt-4 leading-7 text-muted-foreground">Most catalog orders are ready to ship in 3–7 business days. Custom and bulk projects typically take 7–14 business days after design approval. We&apos;ll confirm the exact schedule with your quote.</p></div></section><section className="mt-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">How it works</p><div className="mt-6 grid gap-4 md:grid-cols-4">{steps.map((step, index) => <div key={step} className="border-t-2 border-primary pt-5"><span className="font-mono text-sm text-primary">0{index + 1}</span><p className="mt-3 font-semibold leading-6">{step}</p></div>)}</div></section><div className="mt-16"><Button asChild size="lg"><Link href="/policies/bulk-enquiry">Request a project quote <ArrowRight className="size-4" /></Link></Button></div></main> }

function BulkPage() { return <main className="mx-auto max-w-6xl px-6 py-14 lg:px-8"><PageIntro eyebrow="For teams and events" title="Make a bigger impression, together.">Bulk orders come with better pricing, consistent finishes, and custom branding options for businesses, events, and thoughtful gifts.</PageIntro><div className="mt-12 grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div className="space-y-5 text-muted-foreground"><p className="text-lg leading-8">Tell us what you need and we&apos;ll recommend the right material, production plan, and color palette for your project.</p><div className="space-y-3 border-l-2 border-primary pl-5"><p><strong className="text-foreground">Volume discounts</strong><br />A quote built around your quantity and timeline.</p><p><strong className="text-foreground">Custom branding</strong><br />Colors, logos, and packaging details that feel like your brand.</p><p><strong className="text-foreground">Reliable batches</strong><br />Consistent settings and quality checks across every piece.</p></div></div><div className="border border-border bg-card p-6 sm:p-8"><BulkEnquiryForm /></div></div></main> }

export default async function PolicyPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; if (slug === 'about') return <AboutPage />; if (slug === 'printing-services') return <ServicesPage />; if (slug === 'bulk-enquiry') return <BulkPage />; const policy = mockPolicies[slug]; if (!policy) notFound(); return <main className="mx-auto max-w-3xl px-6 py-16 lg:px-8"><Link href="/" className="text-sm font-semibold text-primary hover:underline">PrintForge</Link><h1 className="mt-8 text-4xl font-bold text-foreground">{policy.title}</h1><div className="mt-8 space-y-5 leading-8 text-muted-foreground">{policy.body.map((paragraph, i) => <p key={i}>{paragraph}</p>)}</div></main> }
